name: Build/Test/Deploy
on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'recursive'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        with:
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: src/.vuepress/dist/
          # CLEAN: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'recursive'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint-ci
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'recursive'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Spellcheck
        run: pnpm spellcheck
